#!/usr/bin/env python3
from __future__ import annotations

import os
from pathlib import Path
import shutil


APP_NAME = "chec_dash_parity"

IGNORE_PATTERNS = shutil.ignore_patterns(
    "__pycache__",
    "*.pyc",
    "*.pyo",
    ".pytest_cache",
)


def _render_app_yaml(template_text: str) -> str:
    gemini_secret_resource_key = os.getenv("APP_GEMINI_SECRET_RESOURCE_KEY", "").strip()
    if gemini_secret_resource_key:
        gemini_api_key_env = (
            "  - name: GEMINI_API_KEY\n"
            f"    valueFrom: \"{gemini_secret_resource_key}\""
        )
    else:
        gemini_api_key_env = "  - name: GEMINI_API_KEY\n    value: \"\""

    replacements = {
        "__WAREHOUSE_ID__": os.getenv("APP_WAREHOUSE_ID", "4437a6195e05c59c"),
        "__CATALOG_NAME__": os.getenv("APP_CATALOG_NAME", "chec_dbx_demo"),
        "__GOLD_SCHEMA__": os.getenv("APP_GOLD_SCHEMA", "gold"),
        "__SILVER_SCHEMA__": os.getenv("APP_SILVER_SCHEMA", "silver"),
        "__CHATBOT_ENABLED__": os.getenv("APP_CHATBOT_ENABLED", "false"),
        "__CHATBOT_CORPUS_VOLUME_RESOURCE_KEY__": os.getenv(
            "APP_CHATBOT_CORPUS_VOLUME_RESOURCE_KEY",
            "chatbot_corpus_volume",
        ),
        "__CHATBOT_CORPUS_SUBDIR__": os.getenv("APP_CHATBOT_CORPUS_SUBDIR", "chatbot_corpus"),
        "__CHATBOT_RETRIEVAL_TOP_K__": os.getenv("APP_CHATBOT_RETRIEVAL_TOP_K", "5"),
        "__CHATBOT_MAX_CONTEXT_CHARS__": os.getenv("APP_CHATBOT_MAX_CONTEXT_CHARS", "12000"),
        "__GEMINI_MODEL__": os.getenv("APP_GEMINI_MODEL", "gemini-2.5-flash"),
        "__GEMINI_API_KEY_ENV__": gemini_api_key_env,
    }
    rendered = template_text
    for placeholder, value in replacements.items():
        rendered = rendered.replace(placeholder, value)
    return rendered


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    databricks_root = repo_root / "databricks"
    template_root = databricks_root / "apps" / APP_NAME
    build_root = databricks_root / "build" / APP_NAME

    if build_root.exists():
        shutil.rmtree(build_root)
    build_root.mkdir(parents=True, exist_ok=True)

    requirements_template = template_root / "requirements.txt"
    shutil.copy2(
        requirements_template if requirements_template.exists() else repo_root / "requirements.txt",
        build_root / "requirements.txt",
    )
    shutil.copy2(repo_root / "run_dash.py", build_root / "run_dash.py")
    shutil.copytree(repo_root / "src", build_root / "src", ignore=IGNORE_PATTERNS)

    shutil.copy2(
        template_root / "databricks_app_wsgi.py",
        build_root / "databricks_app_wsgi.py",
    )

    app_yaml_text = (template_root / "app.yaml").read_text(encoding="utf-8")
    (build_root / "app.yaml").write_text(_render_app_yaml(app_yaml_text), encoding="utf-8")
    (build_root / "README.md").write_text(
        "Generated by stage_phase35_databricks_app.py from the CHEC dashboard repo.\n",
        encoding="utf-8",
    )

    print(f"Staged Databricks app source at {build_root}")


if __name__ == "__main__":
    main()
