#!/usr/bin/env python3
from __future__ import annotations

import os
from pathlib import Path
import shutil


APP_NAME = "chec_dash_parity"

IGNORE_PATTERNS = shutil.ignore_patterns(
    "__pycache__",
    "*.pyc",
    "*.pyo",
    ".pytest_cache",
)


def _render_app_yaml(template_text: str) -> str:
    replacements = {
        "__WAREHOUSE_ID__": os.getenv("APP_WAREHOUSE_ID", "4437a6195e05c59c"),
        "__CATALOG_NAME__": os.getenv("APP_CATALOG_NAME", "chec_dbx_demo"),
        "__GOLD_SCHEMA__": os.getenv("APP_GOLD_SCHEMA", "gold"),
        "__SILVER_SCHEMA__": os.getenv("APP_SILVER_SCHEMA", "silver"),
    }
    rendered = template_text
    for placeholder, value in replacements.items():
        rendered = rendered.replace(placeholder, value)
    return rendered


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    databricks_root = repo_root / "databricks"
    template_root = databricks_root / "apps" / APP_NAME
    build_root = databricks_root / "build" / APP_NAME

    if build_root.exists():
        shutil.rmtree(build_root)
    build_root.mkdir(parents=True, exist_ok=True)

    requirements_template = template_root / "requirements.txt"
    shutil.copy2(
        requirements_template if requirements_template.exists() else repo_root / "requirements.txt",
        build_root / "requirements.txt",
    )
    shutil.copy2(repo_root / "run_dash.py", build_root / "run_dash.py")
    shutil.copytree(repo_root / "src", build_root / "src", ignore=IGNORE_PATTERNS)

    shutil.copy2(
        template_root / "databricks_app_wsgi.py",
        build_root / "databricks_app_wsgi.py",
    )

    app_yaml_text = (template_root / "app.yaml").read_text(encoding="utf-8")
    (build_root / "app.yaml").write_text(_render_app_yaml(app_yaml_text), encoding="utf-8")
    (build_root / "README.md").write_text(
        "Generated by stage_phase35_databricks_app.py from the CHEC dashboard repo.\n",
        encoding="utf-8",
    )

    print(f"Staged Databricks app source at {build_root}")


if __name__ == "__main__":
    main()
